// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLf4h7Jina19UxHBDTnpZe8XC6lrJ0Tw',
    appId: '1:622439856417:web:c52239d4e0c172c7caa660',
    messagingSenderId: '622439856417',
    projectId: 'project-fasum-65292',
    authDomain: 'project-fasum-65292.firebaseapp.com',
    storageBucket: 'project-fasum-65292.firebasestorage.app',
    measurementId: 'G-024P422B5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDz6_K_Jbso7rxOn1r4rTQAv4B4eJC6w',
    appId: '1:622439856417:android:fe7bdb28595f6621caa660',
    messagingSenderId: '622439856417',
    projectId: 'project-fasum-65292',
    storageBucket: 'project-fasum-65292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVqobhW4ZS9Ni2mbImG4SVCUelpW3J2FM',
    appId: '1:622439856417:ios:a72befdc7ea45d3acaa660',
    messagingSenderId: '622439856417',
    projectId: 'project-fasum-65292',
    storageBucket: 'project-fasum-65292.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVqobhW4ZS9Ni2mbImG4SVCUelpW3J2FM',
    appId: '1:622439856417:ios:a72befdc7ea45d3acaa660',
    messagingSenderId: '622439856417',
    projectId: 'project-fasum-65292',
    storageBucket: 'project-fasum-65292.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcLf4h7Jina19UxHBDTnpZe8XC6lrJ0Tw',
    appId: '1:622439856417:web:e407eedb00250945caa660',
    messagingSenderId: '622439856417',
    projectId: 'project-fasum-65292',
    authDomain: 'project-fasum-65292.firebaseapp.com',
    storageBucket: 'project-fasum-65292.firebasestorage.app',
    measurementId: 'G-4R92QVFQ34',
  );
}
